spring:
  datasource:
    password: ${DB_PASSWORD:1453}
    username: ${DB_USERNAME:postgres}
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ms_auth}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

server:
  port: 8084
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

management:
  tracing:
    sampling:
      probability: 1.0