spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ms_payment}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1453}
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
server:
  port: 8083

#management:
#  tracing:
#    sampling:
#      probability: 1.0