spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ms-product}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1453}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update  
server:
  port: 8081
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
#spring:
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest