spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "classpath:/configs/"
        bootstrap: true
  application:
    name: config-server

server:
  port: 8888
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      deafultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}